### ISSUE TITLE
Errors downloading from elfin server at UCLA

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#1059]
I'm getting some errors in one of the elfin tests -- it's having trouble downloading a tplot file for validation.
The error is occurring both in github actions, and on my laptop.

I can open that URL in the browser, but it's failing in Python with a broken connection/incomplete read.

```
Starting elfin epd_l1 tests at Sun Nov 17 19:43:22 UTC 2024
17-Nov-24 19:43:27: Downloading https://data.elfin.ucla.edu/test/validation_elb_epd_l1_raw_20220412.tplot to data/elfin/test/validation_elb_epd_l1_raw_20220412.tplot
E
======================================================================
ERROR: setUpClass (__main__.TestELFL1Validation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/urllib3/response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(97974 bytes read, 137378 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/projects/elfin/tests/test_epd_l1.py", line 35, in setUpClass
    calfile = download(remote_file=calfile_name,
                       remote_path=CONFIG['remote_data_dir'],
                       local_path=CONFIG['local_data_dir'],
                       no_download=False)
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/utilities/download.py", line 526, in download
    resp_data = download_file(
        url=url,
    ...<8 lines>...
        force_download=force_download
    )
  File "/home/runner/work/pyspedas/pyspedas/pyspedas/utilities/download.py", line 234, in download_file
    copyfileobj(fsrc.raw, f)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/shutil.py", line 203, in copyfileobj
    while buf := fsrc_read(length):
                 ~~~~~~~~~^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/urllib3/response.py", line 949, in read
    data = self._raw_read(amt)
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/urllib3/response.py", line 872, in _raw_read
    with self._error_catcher():
         ~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/urllib3/response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(97974 bytes read, 137378 more expected)', IncompleteRead(97974 bytes read, 137378 more expected))

----------------------------------------------------------------------
Ran 0 tests in 1.041s

FAILED (errors=1)
E
```

**Comment by jameswilburlewis** [comment]
Thanks...I can successfully run the ELFIN tests now!
