### ISSUE TITLE
Errors loading MMS FEEPS SITL data

### ISSUE THREAD

**Issue by supervised** [spedas/pyspedas#484]
I'm seeing an error loading recent FEEPS SITL data:

`mms_load_feeps(probe=4, trange=['2022-12-01', '2022-12-02'], level='sitl')`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/print_vars.py", line 8, in wrapper
>     variables = func(*args, **kwargs)
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/feeps/feeps.py", line 101, in mms_load_feeps
>     tvars = mms_load_data(trange=trange, notplot=notplot, probe=probe, data_rate=data_rate, level=level, instrument='feeps',
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/mms_load_data.py", line 197, in mms_load_data
>     new_variables = cdf_to_tplot(filtered_out_files, varformat=varformat, varnames=varnames, get_support_data=get_support_data, prefix=prefix, suffix=suffix, center_measurement=center_measurement, notplot=notplot)
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pytplot/importers/cdf_to_tplot.py", line 413, in cdf_to_tplot
>     depend_1_var_atts = master_cdf_file.varattsget(var_atts['DEPEND_1'])
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cdflib/cdfread.py", line 742, in varattsget
>     raise ValueError(f'No variable by this name: {variable}')
> ValueError: No variable by this name: channel_ids

And a different error while loading older SITL data:

`mms_load_feeps(probe=4, trange=['2017-12-01', '2017-12-02'], level='sitl')`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/print_vars.py", line 8, in wrapper
>     variables = func(*args, **kwargs)
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/feeps/feeps.py", line 131, in mms_load_feeps
>     split_vars = mms_feeps_split_integral_ch(data_unit, datatype, probe, suffix=suffix, data_rate=drate, level=lvl, sensor_eyes=eyes)
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/mms/feeps/mms_feeps_split_integral_ch.py", line 55, in mms_feeps_split_integral_ch
>     time, data, energies = pytplot.get_data(top_name+suffix)
> TypeError: cannot unpack non-iterable NoneType object

**Comment by supervised** [comment]
These should be fixed now
