### ISSUE TITLE
Crash in time_double during pytplot.makegap

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#805]
One of the plot tests is failing now:

```
Error
Traceback (most recent call last):
  File "/Users/jwl/PycharmProjects/pyspedas/pyspedas/utilities/tests/plot_tests.py", line 211, in test_pseudovars_spectra
    tplot(vars, save_png='test_pseudo_spectra_full_burst',display=global_display)
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/tplot.py", line 158, in tplot
    return mpl_tplot(name, var_label=var_label,
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/MPLPlotter/tplot.py", line 221, in tplot
    tplot(var, return_plot_objects=return_plot_objects,
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/MPLPlotter/tplot.py", line 252, in tplot
    var_data = pytplot.makegap(var_data, dt = plot_extras.get('data_gap'))
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/tplot_math/makegap.py", line 54, in makegap
    x = pytplot.time_float(var_data.times)
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/time_double.py", line 85, in time_float
    time_list.append(time_float_one(t))
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/time_double.py", line 35, in time_float_one
    in_datetime = parser.isoparse(s_time)
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
    components, pos = self._parse_isodate(dt_str)
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
    return self._parse_isodate_common(dt_str)
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
    len_str = len(dt_str)
TypeError: object of type 'numpy.datetime64' has no len()

```

**Comment by jameswilburlewis** [comment]
I reverted the change to the way makegap is converting the input timestamps: see https://github.com/MAVENSDC/PyTplot/commit/615e7c429bee7a4c4249a820cfe98b46aa45d641
The call to time_double() was failing because it doesn't know how to handle the np.datetime64 objects it was getting inside makegap.  If there's a case where the "divide by 1e9" method fails, let me know so we can take a closer look and add another regression test.
